server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;

        # Cache-busting headers
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }
}

# upstream app_servers {
#     # Change :3000 to :80
#     server app:80;
# }

# server {
#     listen 80;

#     location / {
#         proxy_pass http://app_servers;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#     }
# }


# ============================

# upstream my_app_pool {
#     # Nginx uses DNS to find all 'app' replicas automatically
#     server app:80; 
# }

# server {
#     listen 80;
#     location / {
#         proxy_pass http://my_app_pool;
#     }
# }