apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:             # <--- This is the layer you are missing
    metadata:
      labels:
        app: my-app
    spec:               # <--- This one is inside template
      containers:
      - name: my-app
        image: high-availability-app:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80